import type { Pyramid } from "./types";

export const fallbackPyramids: Pyramid[] = [
  {
    id: "great-pyramid-giza",
    name: "Gran Piramide de Guiza",
    country: "Egipto",
    region: "Guiza",
    civilization: "Antiguo Egipto",
    period: "c. 2600 a. C.",
    latitude: 29.9792,
    longitude: 31.1342,
    elevationMeters: 60,
    heightMeters: 146.6,
    sourceUrl: "https://www.wikidata.org/wiki/Q37200",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/e/e3/Kheops-Pyramid.jpg",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "pyramid-of-khafre",
    name: "Piramide de Kefren",
    country: "Egipto",
    region: "Guiza",
    civilization: "Antiguo Egipto",
    period: "c. 2570 a. C.",
    latitude: 29.9761,
    longitude: 31.1308,
    elevationMeters: 65,
    heightMeters: 136.4,
    sourceUrl: "https://www.wikidata.org/wiki/Q37218",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/7/77/Khafre%27s_Pyramid.jpg",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "sun-pyramid",
    name: "Piramide del Sol",
    country: "Mexico",
    region: "Teotihuacan",
    civilization: "Teotihuacana",
    period: "c. 200 d. C.",
    latitude: 19.6925,
    longitude: -98.8438,
    elevationMeters: 2285,
    heightMeters: 65,
    sourceUrl: "https://www.wikidata.org/wiki/Q154438",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/5/53/Pyramid_of_the_Sun_in_Teotihuacan.jpg",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "el-castillo",
    name: "El Castillo",
    country: "Mexico",
    region: "Chichen Itza",
    civilization: "Maya",
    period: "c. 900-1200 d. C.",
    latitude: 20.6829,
    longitude: -88.5686,
    elevationMeters: 24,
    heightMeters: 30,
    sourceUrl: "https://www.wikidata.org/wiki/Q201865",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/5/51/El_Castillo_Stitch_2008_Edit_1.jpg",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "temple-i-tikal",
    name: "Templo I de Tikal",
    country: "Guatemala",
    region: "Tikal",
    civilization: "Maya",
    period: "c. 732 d. C.",
    latitude: 17.222,
    longitude: -89.6237,
    elevationMeters: 250,
    heightMeters: 47,
    sourceUrl: "https://www.wikidata.org/wiki/Q208185",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/2/2f/Tikal_Temple1_2006_08_11.JPG",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "pyramid-of-cestius",
    name: "Piramide de Cestio",
    country: "Italia",
    region: "Roma",
    civilization: "Roma antigua",
    period: "c. 12 a. C.",
    latitude: 41.8764,
    longitude: 12.4803,
    elevationMeters: 22,
    heightMeters: 36.4,
    sourceUrl: "https://www.wikidata.org/wiki/Q321115",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/8/88/Piramide_Cestia_%28Rome%29.jpg",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "nubian-pyramids-meroe",
    name: "Piramides de Meroe",
    country: "Sudan",
    region: "Meroe",
    civilization: "Kush",
    period: "c. 300 a. C.-350 d. C.",
    latitude: 16.9365,
    longitude: 33.748,
    elevationMeters: 430,
    heightMeters: 30,
    sourceUrl: "https://www.wikidata.org/wiki/Q182098",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/7/79/Meroe_Pyramids_Sudan.jpg",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "bosnian-pyramid-sun",
    name: "Piramide del Sol de Bosnia",
    country: "Bosnia y Herzegovina",
    region: "Visoko",
    civilization: "Sitio controvertido",
    period: "Clasificacion discutida",
    latitude: 43.9771,
    longitude: 18.1769,
    elevationMeters: 767,
    heightMeters: null,
    sourceUrl: "https://www.wikidata.org/wiki/Q2871182",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/0/06/Visocica.jpg",
    updatedAt: "2026-05-15T00:00:00.000Z",
  },
];
